ePayments/Controllers/TransactionSummaryController.cs
namespace ePayments.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using ePayments.Models;

    public class TransactionSummaryController : Controller
    {
        private readonly ICourseRepository courseRepository;
        private readonly ITransactionService transactionService;

        public TransactionSummaryController() 
            : this(new CourseRepository(), new TransactionService())
        {
        }

        internal TransactionSummaryController(ICourseRepository courseRepository, ITransactionService transactionService)
        {
            this.courseRepository = courseRepository;
            this.transactionService = transactionService;
        }

        public ActionResult Index()
        {
            var reservationReports = this.GetReservationReports().ToList();
            return this.View(reservationReports);
        }

        private IEnumerable<TransactionSummaryViewModel> GetReservationReports()
        {
            var courses = this.courseRepository.GetCourses();
            return
                from course in courses
                let numberOfReservations = this.transactionService.GetNumberOfTransactions(course.Id)
                select new TransactionSummaryViewModel(course, numberOfReservations);
        }

    }
}

ePayments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("bbv Academy", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Transactions", "Index", "TransactionSummary")</li>
                            <li>@Html.ActionLink("Test Data", "Info", "Home")</li>
                            <li>@Html.ActionLink("Documentation", "Documentation", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Oleg, Roland, Ken</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>