ePayments/Controllers/AuthorizeNetController.cs
using System.Web.Mvc;

namespace ePayments.Controllers
{
    using System.Globalization;

    using AuthorizeNet;

    using ePayments.ModelMock;

    public class AuthorizeNetController : Controller
    {
        /// <summary>
        /// Pays the specified id.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns></returns>
        public ActionResult Pay(int id)
        {
            return View(new CreditCardData { ProductId = id.ToString(CultureInfo.InvariantCulture ) });
        }

        /// <summary>
        /// Performs the transaction.
        /// </summary>
        /// <param name="creditCardNumber">The credit card number.</param>
        /// <param name="amount">The amount.</param>
        /// <param name="productId">The product id.</param>
        /// <returns></returns>
        public ActionResult PerformTransaction(int creditCardNumber, decimal amount, string productId)
        {
             // step 1 - create the request
            var request = new AuthorizationRequest(
                creditCardNumber.ToString(CultureInfo.InvariantCulture),
                "1216",
                amount,
                productId.ToString(CultureInfo.InvariantCulture));

            // step 2 - create the gateway, sending in your credentials
            var gate = new Gateway(AuthorizeNetCredentials.API_LOGIN, AuthorizeNetCredentials.TRANSACTION_KEY);

            // step 3 - make some money
            //IGatewayResponse response = gate.Send(request);

            //if (response.Approved)
            //{
            //    return View()
            //}

            return null;
        }
    }
}

ePayments/Views/AuthorizeNet/Pay.cshtml
@model ePayments.ModelMock.CreditCardData

@{
    ViewBag.Title = "PAY! NAU!";
}

<h2>PAY! NAU!</h2>

@using (Html.BeginForm("PerformTransaction", "AuthorizeNet"))
{
    @Html.Hidden("ProductId", Model.ProductId)
    <table>
        <tr>
            <td>Credit card number:</td>
            <td>@Html.TextBox("CreditCardNumber", Model.CreditCardNumber)</td>
        </tr>
        <tr>
            <td>Amount:</td>
            <td>@Html.TextBox("Amount", Model.Amount)</td>
        </tr>
    </table>
    
    <input type="submit" value="Submit"/>
}






ePayments/Views/AuthorizeNet/PaymentSuccessful.cshtml
@model ePayments.ModelMock.CreditCardData

@{
    ViewBag.Title = "PaymentSuccessful";
}

<h2>PaymentSuccessful</h2>